# Generated by Degen (https://github.com/Bystroushaak/Degen)
BIN=kv_login

DC=dmd
CFLAGS=

.PHONY: build
.PHONY: clean
.PHONY: distrib
.PHONY: help

build: $(BIN).d 
	$(DC) -J. modules/*.d $(BIN).d -of$(BIN)
	
run: build
	./$(BIN)