# Generated by Degen (https://github.com/Bystroushaak/Degen)
BIN=kv_login

DC=dmd -gc -debug
CFLAGS=

.PHONY: build
.PHONY: clean
.PHONY: distrib
.PHONY: help

build: $(BIN).d 
	$(DC) -J. $(BIN).d modules/*.d -of$(BIN)
	
run: build
	./$(BIN)